[package]
name = "{{project-name}}"
version = "0.1.0"
edition = "2021"
authors = ["{{authors}}"]

[dependencies]
rocket = { version = "=0.5.0-rc.3" }
tokio = { version = "1.27.0", features = ["full"] }
rocket_dyn_templates = { version = "=0.1.0-rc.3", features = ["tera"] }
